import type { Metadata } from "next";
import Header from "./components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "@redig's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex h-screen flex-col antialiased"}>
        <main className="flex h-full flex-1 flex-col">
          <Header />

          {children}
        </main>
      </body>
    </html>
  );
}
